Added git auto-update feature

diff --git a/script/config b/script/config
--- a/script/config
+++ b/script/config
@@ -1,6 +1,6 @@
 #!/bin/bash
-
 readonly ORIG_DIR=`pwd`
+readonly QUIET="> /dev/null 2>&1"
 
 # Put us where we belong, in the root dir of the repo
 function go_to_repo_root () {
@@ -23,9 +23,10 @@ function is_git_repo() {
 
 function is_clean() {
   local result=""
+  local porcelain=`git status --porcelain`
   # Pending git commit?
-  if [ ! -z `git status --porcelain` ]; then
-    "Boxen has a dirty tree, won't auto-update!"
+  if [ ! -z "$porcelain" ]; then
+    echo "Has a dirty tree, won't auto-update!"
     exit
   fi
 }
@@ -52,12 +53,34 @@ function on_master_branch() {
 
 function has_upstream_changes() {
   local upstream_changes=`git rev-list --count master..origin/master`
-
+  if [ "$upstream_changes" -ne 0 ]; then
+    echo "Upstream repo has changes, won't auto-update!"
+    exit
+  fi
 }
 
 function is_fast_forwardable() {
   local fast_forwardable=`git rev-list --count origin/master..master`
+  if [ "$fast_forwardable" -ne 0 ]; then
+    echo "Master branch is out of sync, won't auto-update!"
+    exit
+  fi
+}
 
+function git_reset() {
+  git reset --hard origin/master $QUIET
+  if [ $? -ne 0 ]; then
+    echo "Git reset failed, won't auto-update!"
+    exit
+  fi
+}
+
+function git_clean() {
+  git clean -qdf
+  if [ $? -ne 0 ]; then
+    echo "Git clean failed, won't auto-update!"
+    exit
+  fi
 }
 
 function auto_update_repo() {
@@ -74,34 +97,7 @@ function auto_update_repo() {
 
 function main() {
   go_to_repo_root
+  auto_update_repo
 }
 
 main
-
-<<COMMENT
-    clean  = `git status --porcelain`.empty?
-    current_branch = `git symbolic-ref HEAD`.chomp
-    master = current_branch == "refs/heads/master"
-
-    upstream_changes = `git rev-list --count master..origin/master`.chomp != '0'
-    fast_forwardable = `git rev-list --count origin/master..master`.chomp == '0'
-
-    elsif !fast_forwardable
-      warn "Boxen's master branch is out of sync, won't auto-update!"
-    elsif !clean
-      warn "Boxen has a dirty tree, won't auto-update!"
-    elsif !upstream_changes
-      warn "Boxen is up-to-date."
-    end
-
-    if clean && master && fast_forwardable && upstream_changes
-      reset   = "(git reset --hard origin/master #{quietly})"
-      reclean = "(git clean -qdf)"
-
-      unless system "#{reset} && #{reclean}"
-        warn "Auto-update of Boxen FAILED, continuing."
-      end
-    end
-  end
-end
-COMMENT
